### PR TITLE
coroc: support generics

### LINKED ISSUE #123: Support functions with type parameters
When compiling functions that have type parameters, `coroc` outputs the following error:
```
syntax error: function type must have no type parameters
```

### PR DESCRIPTION
**Pull request by chriso**
This PR adds initial support for generics.

The guide at https://github.com/golang/proposal/blob/master/design/generics-implementation-dictionaries-go1.18.md has been helpful in understanding how the Go compiler implements generics (via a combination of stenciling and dictionaries).

Fixes #123.

### CODE REVIEW

File: compiler/testdata/coroutine_durable.go [hunk 1]
```diff
@@ -3384,5 +3438,11 @@ func init() {
 	_types.RegisterFunc[func()]("github.com/stealthrocket/coroutine/compiler/testdata.YieldingExpressionDesugaring")
 	_types.RegisterFunc[func(_fn0 int) (_ int)]("github.com/stealthrocket/coroutine/compiler/testdata.a")
 	_types.RegisterFunc[func(_fn0 int) (_ int)]("github.com/stealthrocket/coroutine/compiler/testdata.b")
+	_types.RegisterFunc[func(n int) func()]("github.com/stealthrocket/coroutine/compiler/testdata.buildClosure[go.shape.int]")
+	_types.RegisterClosure[func(), struct {
+		F  uintptr
+		D  uintptr
```
Comment (achille-roussel) [inline compiler/testdata/coroutine_durable.go:3444]: Interesting, so the generic closures hold a pointer to the dictionary as the second field, I misunderstood that detail last time.

File: compiler/testdata/coroutine_durable.go [hunk 2]
```diff
@@ -3252,14 +3252,68 @@ func IdentityGenericInt(n int) { IdentityGeneric[int](n) }
...
+func buildClosure[T any](n T) func() {
+	return func() {
+		coroutine.Yield[T, any](n)
+	}
+}
+
+//go:noinline
+func IdentityGenericClosureInt(n int) { IdentityGenericClosure[int](n) }
 func init() {
+	_types.RegisterFunc[func()]("github.com/stealthrocket/coroutine/compiler/testdata.(*IdentityGenericStruct[go.shape.int]).Run")
```
Comment (achille-roussel) [inline compiler/testdata/coroutine_durable.go:3306]: I'm curious about this, wouldn't the signature of the function be `func(uintptr)` to accept the generic type dictionary as first argument?

Comment (chriso) [reply compiler/testdata/coroutine_durable.go:3306]: I'm not sure, and I'll see if I can create a test case where it fails otherwise.

It's my understanding that when the Go compiler constructs a static call to a method it'll automatically insert the dictionary as the first argument (before the receiver). If you instead take a reference to the method so it can be called dynamically, it'll create a closure with the dictionary automatically bound to the function, and possibly the receiver too depending on how you've taken the reference. In neither case does the dictionary need to be explicitly listed as a parameter?

Comment (achille-roussel) [reply compiler/testdata/coroutine_durable.go:3306]: Ah yeah it might not be needed, there's a parallel indeed with the receiver being passed in a register (DX), the dictionary is given in AX, that's just a modification of the calling convention but not a change in the Go type or function signature 👍

**Review by achille-roussel — APPROVED** [review]
